export const strings = {
  app: {
    title: "NCM 转换器",
    subtitle: "mac desktop",
  },
  nav: {
    convert: "开始转换",
    queue: "当前任务",
    history: "最近结果",
    settings: "偏好设置",
  },
  stats: {
    ncmFiles: "NCM 文件",
    folderMode: "文件夹模式",
    history: "转换记录",
    sources: "个来源",
    done: "完成",
    failed: "失败",
  },
  header: {
    kicker: "Converter",
    title: "转换",
    tagline: "把网易云缓存转成 mp3 或 flac。",
  },
  sections: {
    sourceTitle: "来源",
    sourceDesc: "选择 `.ncm` 文件或整个缓存目录。",
    outputTitle: "保存方式",
    outputDesc: "设置转换后的文件放哪里、同名时怎么处理。",
    queueTitle: "当前任务",
    queueEmpty: "选好的音乐会显示在这里。",
    queueReady: "确认无误后点击开始转换。",
    historyTitle: "转换记录",
    historyEmpty: "转换完成后会自动保留在这里。",
    historyReady: (n: number) => `已保留 ${n} 条最近记录。`,
    recordTitle: "本次结果",
  },
  buttons: {
    clear: "清空",
    start: "开始转换",
    pickFiles: "选择 .ncm 文件",
    pickFilesDesc: "可一次选择多个音乐缓存文件",
    pickFolder: "选择来源文件夹",
    pickFolderDesc: "适合批量处理专辑或缓存目录",
    pickOutput: "选择目录",
    removeOriginal: "转换后删除源文件",
    removeOriginalDesc: "完成后删除 .ncm，谨慎开启",
    recursive: "递归处理子文件夹",
    recursiveDesc: "仅在选择文件夹时生效",
    autoScanDefault: "启动时扫描默认缓存",
    autoScanDefaultDesc: "发现网易云缓存后给出一键加入",
    watchDefaultCache: "自动监听缓存目录",
    watchDefaultCacheDesc: "网易云新下载 .ncm 后提醒加入",
    autoRevealOutput: "完成后打开输出目录",
    autoRevealOutputDesc: "转换结束后自动在 Finder 中显示",
    duplicate: "同名文件",
    duplicateDesc: "遇到已有输出文件时怎么处理",
    organize: "整理目录",
    organizeDesc: "转换完成后按歌手或专辑自动归档",
    checkUpdate: "检查更新",
    checkUpdateDesc: "查看 GitHub Release 是否有新版",
    openRelease: "打开下载",
    jobs: "同时转换",
    jobsDesc: "文件多时可提高速度，机器忙就调低",
    advanced: "高级设置",
    cancel: "取消",
    reveal: "显示",
    retry: "重新转换",
    copyPath: "复制路径",
    deleteRecord: "删除记录",
    details: "详情",
    collapse: "收起",
    clearHistory: "清空记录",
  },
  badges: {
    removeOn: "删除已开启",
    moreFiles: (n: number) => `还有 ${n} 个文件`,
    moreHistory: (n: number) => `还有 ${n} 条记录`,
  },
  defaultCache: {
    found: (n: number) => `发现默认缓存目录中的 ${n} 个 NCM 文件`,
    add: "加入队列",
  },
  history: {
    empty: "还没有转换记录",
  },
  drop: {
    hover: "松开以添加 NCM 文件或文件夹",
    empty: "把 `.ncm` 文件或文件夹拖到这里",
  },
  output: {
    label: "输出目录",
    placeholder: "默认输出到源文件所在位置",
  },
  duplicate: {
    rename: "改名",
    skip: "跳过",
    overwrite: "覆盖",
  },
  organize: {
    none: "不整理",
    artist: "歌手",
    album: "专辑",
  },
  status: {
    waiting: "等待",
    converting: "转换中",
    done: "完成",
    failed: "失败",
  },
  progress: {
    etaSeconds: (n: number) => `剩余 ${n} 秒`,
    etaMinutes: (m: number, s: number) => `剩余 ${m} 分 ${s} 秒`,
    etaAlmostDone: "即将完成",
    unknown: "正在转换…",
    indeterminate: "正在转换…",
  },
  toast: {
    noNcm: "没有找到可转换的 .ncm 文件。",
    cancelled: "已取消",
    defaultCacheAdded: (n: number) => `已加入 ${n} 个默认缓存文件。`,
    newCacheFound: (n: number) => `发现 ${n} 个新的网易云缓存文件。`,
    addedToQueue: (n: number) => `已加入 ${n} 个文件到队列。`,
    convertDone: (ok: number, failed: number) =>
      failed > 0 ? `转换完成：成功 ${ok} 个，失败 ${failed} 个。` : `转换完成：成功 ${ok} 个。`,
    internalError: (msg: string) => `内部任务失败：${msg}`,
    failedToStart: (msg: string) => `无法启动转换器：${msg}`,
    copied: "路径已复制。",
    reconvertAdded: "已加入当前任务，可重新转换。",
    updateFound: (version: string) => `发现新版 ${version}。`,
    upToDate: (version: string) => `当前已是最新版 ${version}。`,
  },
} as const;
